# yq '. | explode(.)' .github/_std.yml >| .github/workflows/std.yml
name: Standard CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: std-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  discover:
    outputs:
      hits: ${{ steps.discovery.outputs.hits }}
    runs-on: ubuntu-latest
    steps:
      - uses: nixbuild/nix-quick-install-action@v28
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: divnix/std-action/discover@main
        id: discovery
  apps:
    needs: discover
    name: ${{ matrix.target.jobName }}
    runs-on: ubuntu-latest
    if: fromJSON(needs.discover.outputs.hits).apps.build != ''
    strategy:
      matrix:
        target: ${{ fromJSON(needs.discover.outputs.hits).apps.build }}
    steps:
      - uses: nixbuild/nix-quick-install-action@v28
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: divnix/std-action/run@main
  packages:
    needs: discover
    name: ${{ matrix.target.jobName }}
    runs-on: ubuntu-latest
    steps:
      - uses: nixbuild/nix-quick-install-action@v28
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: divnix/std-action/run@main
    if: fromJSON(needs.discover.outputs.hits).packages.build != ''
    strategy:
      matrix:
        target: ${{ fromJSON(needs.discover.outputs.hits).packages.build }}
  devshells:
    needs: discover
    name: ${{ matrix.target.jobName }}
    runs-on: ubuntu-latest
    steps:
      - uses: nixbuild/nix-quick-install-action@v28
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: divnix/std-action/run@main
    if: fromJSON(needs.discover.outputs.hits).devshells.build != ''
    strategy:
      matrix:
        target: ${{ fromJSON(needs.discover.outputs.hits).devshells.build }}
